---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes

  - name: install nginx package
    apt:
      name: nginx
      state: latest

  - name: resource monitor
    apt:
      name: htop
      state: latest
